#!/bin/bash

URL="https://lookingglass.pccwglobal.com/"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SCRIPT="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
SHA="$SCRIPT-sha"

cOUT="$( curl -s -L $URL)"
sOUT="$( echo $cOUT | sha256sum )"

sEmail="alert@kurtcms.org"
rEmail="kurtcms@gmail.com"
EmailS="Each change is stored in a separated file."
EmailC="$URL has been changed"

if [ ! -f $DIR/$SHA ]; then
    echo $sOUT > $DIR/$SHA
else
    if [[ $(echo $cOUT | sha256sum -c $DIR/$SHA --quiet) ]]; then
        echo $cOUT > $DIR/"$SCRIPT-curl-output-$( date +"%Y-%m-%d-%H-%M-%S" )"
        echo $sOUT > $DIR/$SHA
        echo $EmailC | mail -s $EmailS -r $sEmail $rEmail
        # crontab -l | grep -v "$SCRIPT" | crontab -
    fi
fi
